### PR TITLE
Allow for configurable TCP/UDP service names.

### PR DESCRIPTION
**Pull request by lkeijser**
# What this PR does / why we need it
Allow for configurable TCP/UDP service names. As of now, the input service name is hardcoded to graylog-udp/-tcp. This might not be desirable in certain environments.

# Which issue this PR fixes
N/A
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #
N/A

# Special notes for your reviewer
N/A

# Checklist

- [x] [DCO](https://github.com/KongZ/charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by KongZ** [comment]
@lkeijser can you give me an example which circumstance you need to name the service name?

**Comment by lkeijser** [comment]
Well, this applies to the company I work for atm, where all applications log to a specific service name. This MR will keep functionality the same, but allows people like me to specify a different name. The alternative for us is to reconfigure 50 applications.

**Comment by KongZ** [comment]
Thanks for explanation. Can you update [README](https://github.com/KongZ/charts/blob/main/charts/graylog/README.md#configuration) and add `graylog.input.tcp.service.name` to configuration table

**Comment by KongZ** [comment]
@lkeijser you miss `graylog.input.udp.service.name`

**Comment by lkeijser** [comment]
Whoops. I'll add it.

**Review by KongZ — APPROVED** [review]

**Pull request merged**
