### PR TITLE
Added support for a proxy server when downloading the metrics plugin.

### PR DESCRIPTION
**Pull request by lkeijser**
Signed-off-by: Leon Keijser <leon.keijser@proxy.nl>

# What this PR does / why we need it

This allows one to specify a proxy server to download the prometheus metrics plugin. Some users will want this, when their graylog instance is behind a webproxy and blocking normal traffic to an external website.

# Which issue this PR fixes

N/A

# Special notes for your reviewer

The proxy server is set right before downloading the plugin, and disabled immediately afterwards. This is because graylog does an internal self health-check on its own URI. If the proxy server would still be enabled at this point, the health check would fail.

# Checklist

- [ x] [DCO](https://github.com/KongZ/charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped

### CODE REVIEW

**Comment by KongZ** [comment]
Can you change to `graylog.plugins.proxy.enabled` and `graylog.plugins.proxy.host`? And move code script to line https://github.com/KongZ/charts/blob/a5202741c40bd692c5c143303f36edabb5bb3815/charts/graylog/templates/configmap.yaml#L175 and unset before start a graylog. So it can cover all downloading plugins.

**Comment by lkeijser** [comment]
> Can you change to `graylog.plugins.proxy.enabled` and `graylog.plugins.proxy.host`? And move code script to line
> 
> https://github.com/KongZ/charts/blob/a5202741c40bd692c5c143303f36edabb5bb3815/charts/graylog/templates/configmap.yaml#L175
> and unset before start a graylog. So it can cover all downloading plugins.

I think that would conflict with that exact line (175). It loops over the graylog.plugins list. It would treat the settings (enabled / host) as a plugin, don't you think? Perhaps if it's changed to something like this:

```
  plugins:
    ## If true, set proxy server to retrieve the plugins
    ##
    proxy:
      enabled: false
      host: http://your.proxy.host:8080

    jars: []
    # - name: graylog-plugin-slack-notification-4.1.1.jar
    #   url: https://github.com/KongZ/graylog-plugin-slack-notification/releases/download/v4.1.1/graylog-plugin-slack-notification-4.1.1.jar
    # - name: graylog-plugin-function-check-diff-1.0.1.jar
    #   url: https://github.com/KongZ/graylog-plugin-function-check-diff/releases/download/v1.0.1/graylog-plugin-function-check-diff-1.0.1.jar
    # - name: graylog-plugin-google-cloud-pubsub-1.0.4.jar
    #   url: https://github.com/KongZ/graylog-plugin-google-cloud-pubsub/releases/download/v1.0.4/graylog-plugin-google-cloud-pubsub-1.0.4.jar
    # - name: graylog-plugin-auth-sso-3.3.0.jar
    #   url: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/3.3.0/graylog-plugin-auth-sso-3.3.0.jar
```

And then loop over them (jars)

```
    # Download plugins
  {{- if .Values.graylog.plugins.jars }}
    echo "Downloading Graylog Plugins..."
  {{- range .Values.graylog.plugins.jars }}
    echo "Downloading {{ .url }} ..."
```

**Comment by KongZ** [comment]
yes, I miss it. I think using `locations` instead of `jars` is better because it is also supporting *.gz files.
We will have a little migration but it is fine :)

**Comment by lkeijser** [comment]
I've moved the 'export proxy' part to 173 instead of 175. Like this, the proxy will be set even if graylog.plugins.locations is empty, so that when you only define graylog.metrics.enabled, the proxy settings are still applied. Hope this makes sense :)

**Review by KongZ — APPROVED** [review]

**Pull request merged**
