### PR TITLE
Support supplying probes with custom paths and ports in case of a more custom setup

### PR DESCRIPTION
**Pull request by Devil-Shinji**
# What this PR does / why we need it

This PR supports further customization of startupProbe, livenessProbe and readinessProbe to take into account any custom paths and/or ports that might be in use instead of the defaults

# Which issue this PR fixes

-

# Special notes for your reviewer

-

# Checklist

- [x] [DCO](https://github.com/KongZ/charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by KongZ** [comment]
Why you want to change the probe path and port?

**Comment by Devil-Shinji** [comment]
> Why you want to change the probe path and port?

I would like to change those to take into account more customized values in case of GRAYLOG_HTTP_BIND_ADDRESS environment variable. If this is already considered then something else caused a probe failure and restart loop on my end.

**Comment by KongZ** [comment]
@Devil-Shinji you can't change to other values. This is fixed to Graylog server health check address

**Comment by Devil-Shinji** [comment]
> @Devil-Shinji you can't change to other values. This is fixed to Graylog server health check address

Alright, in this case disregard this PR 😅

**Pull request closed without merging**
