### PR TITLE
Change references of deprecated stable/graylog

### PR DESCRIPTION
**Pull request by oscarlofwenhamn**
# What this PR does / why we need it
Graylog README references deprecated chart, not this one. This PR updates these references, and updates a link previously leading to old chart. 

# Checklist

- [x] [DCO](https://github.com/{{ .GitHubOrg }}/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by oscarlofwenhamn** [comment]
```
2020-11-23 08:17:44 [INFO]   File:[charts/graylog/Chart.yaml]
2020-11-23 08:17:44 [ERROR]   Found errors in [kubeval] linter!
2020-11-23 08:17:44 [ERROR]   Error code: 1. Command run:[$ERR  - charts/graylog/Chart.yaml: Missing 'metadata' key]
```

I'm guessing the linter expects the yaml to be a Kubernetes manifest, seeing as I haven't removed any "metadata" key. Reconfiguration required?

**Comment by KongZ** [comment]
@oscarlofwenhamn i just set it to false. Can you merge and try again.
https://github.com/KongZ/charts/blob/main/.github/workflows/linter.yml#L20

**Comment by oscarlofwenhamn** [comment]
Getting some errors from the `Run chart-testing (install)` step that I don't think are coming from the chart, unless I'm missing something. Looks like there are issues in the environment where it tries to install perhaps?

**Comment by KongZ** [comment]
@oscarlofwenhamn i have fixed the ct install on another PR. Please pull from `main` and bump a chart version.

**Comment by oscarlofwenhamn** [comment]
Tests successful, awaiting approval. 
@KongZ, thanks for quick help with sorting out the tests in question! 👍

**Review by KongZ — APPROVED** [review]

**Pull request merged**
