### PR TITLE
resolves #32 - adds support for TLS offload in front of graylog

### LINKED ISSUE #32: chart assumes client uses http if tls is not enabled directly on graylog
Problem is, if you f.ex. have a traefik in front and it manages certificates (and terminates TLS connection there), then I would like to set external_uri to https://mygraylogurl - instead of chart forcing http:// on everything :)

This is unfortunately very embedded in chart.. I'll try to do a PR if you'll accept this ?
Plan would be to add an externalUriTLS Boolean setting - and if thats true, override to use https in urls no matter what tls is set to.

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
@KongZ resolved #32  - hope you agree :)

# What this PR does / why we need it
adds support for TLS offload in front of graylog - without having to have graylog running tls with its manual cert setup.

- fixes #32 

# Checklist

- [ x] [DCO](https://github.com/KongZ/charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Chart Version bumped

### CODE REVIEW

**Comment by KongZ** [comment]
@KlavsKlavsen LGTM. Please update a new value in [README.md](https://github.com/KongZ/charts/blob/main/charts/graylog/README.md ) too.

**Comment by KlavsKlavsen** [comment]
added

**Comment by KongZ** [comment]
Did you forgot to commit README.md?

**Comment by KlavsKlavsen** [comment]
Lol @KongZ - those pesky details.. the push part slipped appearently :)
Pushed now.

**Review by KongZ — APPROVED** [review]

**Pull request merged**
